### ISSUE TITLE
SDC on virtualbox/vagrant?

### ISSUE THREAD

**Issue by chefhoobajoob** [joyent/triton#186]
This is probably a dumb question. I'm a complete smartos ecosystem ignoramus trying to come up to speed, but noticed that while it seems pretty straightforward to get a Dev system going with smartos virtualbox boxes and even some Vagrant plugins for zone management, for some reason this doesn't seem to be the case for open source sdc.

So, why is the case? Is something like this in the works, not technically feasible, too large an effort, or just not of interest?

There is coal, but there sure seem to be a lot of caveats listed for it if you're running anything other than a Mac. Any insight here would be appreciated.

**Comment by jclulow** [comment]
It's not a dumb question, but unfortunately there's no particularly enlightening answer, either.  The main reason that COAL runs "best" (or, at least, is best documented) on VMware Fusion is because that's what we most of us at Joyent use when we are working on SDC components.  I'm also not sure if the bridged/shared-with-host networking options available in VirtualBox are as full-featured as those available in VMware.

Additionally, while it might make sense to try out SmartOS inside Vagrant, as SmartOS is basically a standalone hypervisor, I think it would not be a great fit for managing SDC.  SDC has a much richer (potentially multiple-host) orchestration stack, with more configuration both possible and required: things like user accounts, networks, packages, images, etc.  Having Vagrant try and shield the operator from these features of SDC would likely be missing the point of using SDC at all, instead of just using vanilla SmartOS.

If you're keen to try SDC in VirtualBox, I would grab the USB install image and create a VM with both the USB image you downloaded and a large (blank) virtual disk on which to create the ZFS pool.  Add a virtual NIC for the `admin` network, which should be a host-only network, and a virtual NIC for the `external` network, which should probably be a NAT or "can contact the host and the Internet" network.  The installer asks a fair few questions, but they are relatively simple to answer and there are suggestions in the `sdc.git` README.

You can also join `#smartos` on Freenode (IRC), or [the mailing lists](https://wiki.smartos.org/display/DOC/Mailing+Lists+and+IRC) and ask questions if you get stuck.

**Comment by chefhoobajoob** [comment]
I can see looking to Vagrant to act as a management facade for SDC as missing the point.

I had a more narrow objective of just wanting to give manta a spin, which can apparently only run on top of sdc, where I ran into this speedbump.

I may try to spin up sdc on VirtualBox, time allowing. Thanks for the feedback and the resource pointers.

**Comment by rmustacc** [comment]
The most important thing for VirtualBox is to make sure that you properly set up promiscuous mode inside of VirtualBox on the devices.

**Comment by chefhoobajoob** [comment]
I suppose I'll have to dig in before I can ask what "properly" means. Not sure what I'm in for yet.

**Comment by cheapRoc** [comment]
Going to close this one too since it appears this isn't really an issue as much as a feature request or suggestion that isn't officially supported. Please feel free to hit us up on IRC or the mailing list as suggest above, thanks!
