### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by DarkBlaez** [joyent/triton#231]
In looking at some of the outstanding issues which date back to 2015, is this open sourcing of SDC/Triton dead? There seems to be very little engagement as compared to other full stack opern source efforts. More of a curiosity so I know where to spend my time.

Thanks
DB

**Comment by tgross** [comment]
Hi @DarkBlaez! The open sourcing of Triton is alive and well, but you might find that GitHub issues are better targeted towards the [specific repos](https://github.com/joyent/triton/blob/master/docs/developer-guide/repos.md) for the various subcomponents. Most components are code-reviewed via [Gerrit](https://github.com/joyent/triton/blob/master/CONTRIBUTING.md) rather than here on GitHub, so that may be contributing to your perception of lack of movement. There's also a [mailing list and IRC channel](https://github.com/joyent/triton/blob/master/README.md#community) that are very active, and might be a better spot for support-type questions like #230

I'll admit it looks like we could use some GitHub issue grooming though. 😊

**Comment by mytototo** [comment]
> I'll admit it looks like we could use some GitHub issue grooming though. 😊

@tgross Please do. I needed to search "Is Joyent Triton dead" on Google to make sure the project is still alive and well maintained. The first result was this issue.
