### ISSUE TITLE
Service "cainstsvc" is always in maintenance 

### ISSUE THREAD

**Issue by mk-luo** [joyent/triton#247]
I followed the docs to set up the headnode, all services on the headnode are online except "svc:/smartdc/agent/ca/cainstsvc:default".

maintenance     7:47:28 svc:/smartdc/agent/ca/cainstsvc:default
[root@headnode (whd) ~]# uname -a
SunOS headnode 5.11 joyent_20181026T222507Z i86pc i386 i86pc

I deployed headone on vmware.

**Comment by twhiteman** [comment]
That is likely this issue here:
https://smartos.org/bugview/TRITON-766

You can verify by looking at the log file for that service, e.g.:
```
tail -n 50 $(svcs -L cainstsvc)
```

You can ignore this service error for the most part - but just note that some `sdcadm` commands may refuse to run without this service being enabled/running.

@rmustacc can you take a look at the patch in:
https://github.com/rmustacc/node-ctype/pull/65

**Comment by mk-luo** [comment]
@twhiteman Yes , I checked the log, they are the same issue: https://smartos.org/bugview/TRITON-766. Thanks for the information.

**Comment by mk-luo** [comment]
I will close this issue since it's the same with https://smartos.org/bugview/TRITON-766
